# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'train.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QComboBox,
    QFrame, QGroupBox, QHBoxLayout, QLabel,
    QLineEdit, QProgressBar, QPushButton, QSizePolicy,
    QSpinBox, QWidget)

class Ui_TrainFrame(object):
    def setupUi(self, TrainFrame):
        if not TrainFrame.objectName():
            TrainFrame.setObjectName(u"TrainFrame")
        TrainFrame.resize(695, 571)
        TrainFrame.setCursor(QCursor(Qt.ArrowCursor))
        self.layoutWidget = QWidget(TrainFrame)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(20, 30, 651, 26))
        self.horizontalLayout_3 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.layoutWidget)
        self.label.setObjectName(u"label")

        self.horizontalLayout_3.addWidget(self.label)

        self.lineEdit = QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName(u"lineEdit")

        self.horizontalLayout_3.addWidget(self.lineEdit)

        self.pushButton_4 = QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        sizePolicy = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QSize(20, 0))
        self.pushButton_4.setMaximumSize(QSize(20, 16777215))

        self.horizontalLayout_3.addWidget(self.pushButton_4)

        self.groupBox = QGroupBox(TrainFrame)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 140, 651, 321))
        self.comboBox = QComboBox(self.groupBox)
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(90, 60, 231, 22))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 50, 71, 41))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 94, 72, 22))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(170, 94, 119, 22))
        self.spinBox = QSpinBox(self.groupBox)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(110, 94, 42, 22))
        self.spinBox.setValue(25)
        self.spinBox_2 = QSpinBox(self.groupBox)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(260, 94, 42, 22))
        self.spinBox_2.setValue(7)
        self.spinBox_3 = QSpinBox(self.groupBox)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(560, 94, 61, 22))
        self.spinBox_3.setValue(3)
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(330, 94, 221, 22))
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 130, 72, 22))
        self.spinBox_4 = QSpinBox(self.groupBox)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setGeometry(QRect(120, 130, 61, 22))
        self.spinBox_4.setMaximum(99999)
        self.spinBox_4.setStepType(QAbstractSpinBox.AdaptiveDecimalStepType)
        self.spinBox_4.setValue(1000)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(210, 130, 132, 22))
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(410, 130, 72, 22))
        self.comboBox_3 = QComboBox(self.groupBox)
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(480, 130, 141, 22))
        self.checkBox = QCheckBox(self.groupBox)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(340, 60, 161, 20))
        self.checkBox.setChecked(True)
        self.groupBox_2 = QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 170, 611, 131))
        self.comboBox_2 = QComboBox(self.groupBox_2)
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(90, 30, 121, 22))
        self.label_10 = QLabel(self.groupBox_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 30, 72, 22))
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 70, 72, 22))
        self.spinBox_6 = QSpinBox(self.groupBox_2)
        self.spinBox_6.setObjectName(u"spinBox_6")
        self.spinBox_6.setGeometry(QRect(90, 70, 121, 22))
        self.spinBox_6.setMaximum(99999)
        self.spinBox_6.setStepType(QAbstractSpinBox.AdaptiveDecimalStepType)
        self.spinBox_6.setValue(960)
        self.label_13 = QLabel(self.groupBox_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(240, 70, 101, 22))
        self.comboBox_4 = QComboBox(self.groupBox_2)
        self.comboBox_4.addItem("")
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(330, 70, 101, 22))
        self.label_14 = QLabel(self.groupBox_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 100, 141, 22))
        self.spinBox_7 = QSpinBox(self.groupBox_2)
        self.spinBox_7.setObjectName(u"spinBox_7")
        self.spinBox_7.setGeometry(QRect(150, 100, 61, 22))
        self.spinBox_7.setMaximum(99999)
        self.spinBox_7.setStepType(QAbstractSpinBox.AdaptiveDecimalStepType)
        self.spinBox_7.setValue(10)
        self.label_16 = QLabel(self.groupBox_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(240, 100, 141, 22))
        self.lineEdit_2 = QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(380, 100, 51, 22))
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(510, 60, 72, 22))
        self.lineEdit_5 = QLineEdit(self.groupBox)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(570, 60, 51, 22))
        self.pushButton_7 = QPushButton(self.groupBox)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(420, 20, 101, 31))
        self.pushButton_8 = QPushButton(self.groupBox)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(530, 20, 101, 31))
        self.lineEdit_6 = QLineEdit(self.groupBox)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(350, 130, 51, 22))
        self.layoutWidget_2 = QWidget(TrainFrame)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(20, 60, 651, 26))
        self.horizontalLayout_4 = QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.layoutWidget_2)
        self.label_5.setObjectName(u"label_5")

        self.horizontalLayout_4.addWidget(self.label_5)

        self.lineEdit_3 = QLineEdit(self.layoutWidget_2)
        self.lineEdit_3.setObjectName(u"lineEdit_3")

        self.horizontalLayout_4.addWidget(self.lineEdit_3)

        self.pushButton_5 = QPushButton(self.layoutWidget_2)
        self.pushButton_5.setObjectName(u"pushButton_5")
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QSize(20, 0))
        self.pushButton_5.setMaximumSize(QSize(20, 16777215))

        self.horizontalLayout_4.addWidget(self.pushButton_5)

        self.layoutWidget_3 = QWidget(TrainFrame)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(20, 91, 651, 26))
        self.horizontalLayout_5 = QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label_7 = QLabel(self.layoutWidget_3)
        self.label_7.setObjectName(u"label_7")

        self.horizontalLayout_5.addWidget(self.label_7)

        self.lineEdit_4 = QLineEdit(self.layoutWidget_3)
        self.lineEdit_4.setObjectName(u"lineEdit_4")

        self.horizontalLayout_5.addWidget(self.lineEdit_4)

        self.pushButton_6 = QPushButton(self.layoutWidget_3)
        self.pushButton_6.setObjectName(u"pushButton_6")
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QSize(20, 0))
        self.pushButton_6.setMaximumSize(QSize(20, 16777215))

        self.horizontalLayout_5.addWidget(self.pushButton_6)

        self.pushButton = QPushButton(TrainFrame)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QRect(20, 470, 101, 41))
        self.progressBar = QProgressBar(TrainFrame)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(90, 530, 581, 23))
        self.progressBar.setValue(62)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(Qt.Horizontal)
        self.progressBar.setTextDirection(QProgressBar.TopToBottom)
        self.progressBar.setFormat(u"%p%")
        self.pushButton_2 = QPushButton(TrainFrame)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(140, 470, 101, 41))
        self.pushButton_3 = QPushButton(TrainFrame)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(260, 470, 101, 41))
        self.label_15 = QLabel(TrainFrame)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 530, 72, 22))
#if QT_CONFIG(shortcut)
        self.label.setBuddy(self.lineEdit)
        self.label_2.setBuddy(self.comboBox)
        self.label_3.setBuddy(self.spinBox)
        self.label_6.setBuddy(self.spinBox_2)
        self.label_8.setBuddy(self.spinBox_3)
        self.label_9.setBuddy(self.spinBox_4)
        self.label_11.setBuddy(self.comboBox_3)
        self.label_10.setBuddy(self.comboBox_2)
        self.label_12.setBuddy(self.spinBox_6)
        self.label_13.setBuddy(self.comboBox_4)
        self.label_14.setBuddy(self.spinBox_7)
        self.label_16.setBuddy(self.lineEdit_2)
        self.label_17.setBuddy(self.lineEdit_5)
        self.label_5.setBuddy(self.lineEdit_3)
        self.label_7.setBuddy(self.lineEdit_4)
#endif // QT_CONFIG(shortcut)

        self.retranslateUi(TrainFrame)

        QMetaObject.connectSlotsByName(TrainFrame)
    # setupUi

    def retranslateUi(self, TrainFrame):
        TrainFrame.setWindowTitle(QCoreApplication.translate("TrainFrame", u"\u9ad8\u5149\u8c31\u56fe\u50cf\u5206\u7c7b\u6a21\u578b\u8bad\u7ec3", None))
        self.label.setText(QCoreApplication.translate("TrainFrame", u"\u56fe\u50cf\u4f4d\u7f6e\uff1a", None))
        self.lineEdit.setText(QCoreApplication.translate("TrainFrame", u"D:\\Datasets\\IP\\Indian_pines_corrected.mat", None))
        self.pushButton_4.setText(QCoreApplication.translate("TrainFrame", u"...", None))
        self.groupBox.setTitle(QCoreApplication.translate("TrainFrame", u"\u8bad\u7ec3\u8bbe\u7f6e", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("TrainFrame", u"GPU0: NVIDIA GeForce RTX 3080 Ti", None))

        self.label_2.setText(QCoreApplication.translate("TrainFrame", u"\u8bad\u7ec3\u8bbe\u5907\uff1a", None))
        self.label_3.setText(QCoreApplication.translate("TrainFrame", u"\u56fe\u50cf\u5757\u5927\u5c0f\uff1a", None))
        self.label_6.setText(QCoreApplication.translate("TrainFrame", u"\u4e3b\u6210\u5206\uff08PC\uff09\uff1a", None))
        self.label_8.setText(QCoreApplication.translate("TrainFrame", u"\u6269\u5c55\u5f62\u6001\u5b66\u5206\u6790\uff08EMP\uff09\u4e2d\u5f00\u95ed\u8fd0\u7b97\u6b21\u6570\uff1a", None))
        self.label_9.setText(QCoreApplication.translate("TrainFrame", u"\u8bad\u7ec3\u8fed\u4ee3\u6b21\u6570\uff1a", None))
        self.label_4.setText(QCoreApplication.translate("TrainFrame", u"\u6bcf\u7c7b\u4f7f\u7528\u8bad\u7ec3\u6837\u672c\u6570\u91cf\uff1a", None))
        self.label_11.setText(QCoreApplication.translate("TrainFrame", u"\u6570\u636e\u589e\u5f3a\uff1a", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("TrainFrame", u"E-RAP", None))

        self.checkBox.setText(QCoreApplication.translate("TrainFrame", u"\u81ea\u52a8\u6df7\u5408\u7cbe\u5ea6\u8bad\u7ec3\uff08AMP\uff09", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("TrainFrame", u"\u6a21\u578b\u8bbe\u7f6e", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("TrainFrame", u"EmbGCN", None))

        self.label_10.setText(QCoreApplication.translate("TrainFrame", u"\u5206\u7c7b\u6a21\u578b\uff1a", None))
        self.label_12.setText(QCoreApplication.translate("TrainFrame", u"\u5d4c\u5165\u5927\u5c0f\uff1a", None))
        self.label_13.setText(QCoreApplication.translate("TrainFrame", u"\u5d4c\u5165\u5408\u5e76\u65b9\u5f0f\uff1a", None))
        self.comboBox_4.setItemText(0, QCoreApplication.translate("TrainFrame", u"Max", None))

        self.label_14.setText(QCoreApplication.translate("TrainFrame", u"\u6784\u5efa\u56fe\u65f6\u7684\u8fd1\u90bb\u6570\u91cf\uff1a", None))
        self.label_16.setText(QCoreApplication.translate("TrainFrame", u"\u53c2\u6570\u4e22\u5f03\u7387\uff08Dropout\uff09\uff1a", None))
        self.lineEdit_2.setText(QCoreApplication.translate("TrainFrame", u"0.5", None))
        self.label_17.setText(QCoreApplication.translate("TrainFrame", u"\u5b66\u4e60\u7387\uff1a", None))
        self.lineEdit_5.setText(QCoreApplication.translate("TrainFrame", u"0.0003", None))
        self.pushButton_7.setText(QCoreApplication.translate("TrainFrame", u"\u5bfc\u5165\u8bbe\u7f6e", None))
        self.pushButton_8.setText(QCoreApplication.translate("TrainFrame", u"\u5bfc\u51fa\u8bbe\u7f6e", None))
        self.lineEdit_6.setText(QCoreApplication.translate("TrainFrame", u"4", None))
        self.label_5.setText(QCoreApplication.translate("TrainFrame", u"\u6807\u6ce8\u6587\u4ef6\u4f4d\u7f6e\uff1a", None))
        self.lineEdit_3.setText(QCoreApplication.translate("TrainFrame", u"D:\\Datasets\\IP\\Indian_pines_gt.mat", None))
        self.pushButton_5.setText(QCoreApplication.translate("TrainFrame", u"...", None))
        self.label_7.setText(QCoreApplication.translate("TrainFrame", u"\u8bad\u7ec3\u6743\u91cd\u4fdd\u5b58\u4f4d\u7f6e\uff1a", None))
        self.lineEdit_4.setText(QCoreApplication.translate("TrainFrame", u"D:\\Weights\\IP\\EmbGCN_Exteneded_RAP.pt", None))
        self.pushButton_6.setText(QCoreApplication.translate("TrainFrame", u"...", None))
        self.pushButton.setText(QCoreApplication.translate("TrainFrame", u"\u5f00\u59cb\u8bad\u7ec3", None))
        self.pushButton_2.setText(QCoreApplication.translate("TrainFrame", u"\u6682\u505c\u8bad\u7ec3", None))
        self.pushButton_3.setText(QCoreApplication.translate("TrainFrame", u"\u4e2d\u6b62\u8bad\u7ec3", None))
        self.label_15.setText(QCoreApplication.translate("TrainFrame", u"\u8bad\u7ec3\u8fdb\u5ea6\uff1a", None))
    # retranslateUi

